### PR TITLE
Testbranch

### PR DESCRIPTION
**Pull request by NicholasNagy**
Added Parent signup testing
Added Teacher signup testing
Added router/view for teacher signup testing

This resolves issue #52 which is test case 1

### CODE REVIEW

**Comment by NicholasNagy** [comment]
New update fixes issue #60

**Comment by NicholasNagy** [comment]
Before committing, just download the file and check to see if you can post and comment

**Comment by emiletab** [comment]
Great work!

**Comment by emiletab** [comment]
Great Work!

**Pull request merged**
